* Algoritmos
Este repositorio contiene las prácticas de la asigatura de Algoritmos de la Universidad De A Coruña en el grado de ingeniería informática segundo curso de 2021/2022  

** Trabajo realizado por:
- Miguel López López
- Xoel Díaz Préstamo
- Ángel Gómez Prol

** Contenido de cada práctica
Hay cuatro prácticas con su contenido separado en carpetas individuales, cada una de ellas cuenta con un pdf con los ejercicios a completas, un archivo .c con el código y un informe con la contestación, explicación y análisis.

*** [[https://github.com/migueldeoleiros/Algoritmos/tree/main/p1][Práctica 1]]
Consiste en comparar el funcionamiento de dos algoritmos que calculan la suma de la subsecuencia máxima de un vector dado. La correcta implementación en C de ambos algoritmos y comprobación empírica de la complejidad teórica. 

*** [[https://github.com/migueldeoleiros/Algoritmos/tree/main/p2][Práctica 2]]
Consiste en comparar el funcionamiento de dos algoritmos de ordelanción (*Selección* y *Shell*). La correcta implementación en C de ambos algoritmos y comprobación empírica de la complejidad teórica. 

*** [[https://github.com/migueldeoleiros/Algoritmos/tree/main/p3][Práctica 3]]
Consiste en comparar el funcionamiento de otros dos algoritmos de ordelanción (*Inserción* y *QuickSort*). La correcta implementación en C de ambos algoritmos y comprobación empírica de la complejidad teórica. 
En este caso QuickSort será implementado con selección de pivote por mediana de tres y debemos comparar su funcionamiento con tres umbrales diferentes 1,10 y 100.

*** [[https://github.com/migueldeoleiros/Algoritmos/tree/main/p4][Práctica 4]]
Consiste en implementar el algoritmo de búsqueda del árbol de recubrimiento mínimo de un árbol y comprobación empírica de la complejidad teórica. 
El árbol a procesar será dado por una mariz de adyacencia y el resultado lo debuelve una cola circular en base a vectores.
